### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by opello** [pyrohaz/STM32F0-HMC5883_Barebones#1]
I noticed your [STM32F0-HMC5883L_Test1](https://github.com/pyrohaz/STM32F0-HMC5883L_Test1/blob/45da9824642596b913d942412731179d314aeffc/README.md) project currently claims CC BY-SA.  I was wondering if you were aware that Creative Commons [recommends against using its licenses for software](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_use_a_Creative_Commons_license_for_software.3F)?

I think the [2-Clause BSD license](http://opensource.org/licenses/BSD-2-Clause) would be a good alternative which is still simple and credits your contribution.

If you're willing to include a license for this project, [GitHub has some helpful documentation for choosing a license](https://help.github.com/articles/open-source-licensing/).

Thanks for your time.

**Comment by pyrohaz** [comment]
As far as I remember, that was an old repository that I wasn't using anymore! I've deleted it now. Thank you for checking this!

**Comment by opello** [comment]
I found it [via this blog post of yours](http://hsel.co.uk/2014/05/29/hmc5883l-magnetometer/).

**Comment by opello** [comment]
Looks like this is closed in 1cf6ddc14575e28bec3bf453812e4496826e1fa5.  Thanks!
